### ISSUE TITLE
Lotus is a homosexual and spez pulled his cock out in vc with XDGRC. 

### ISSUE THREAD

**Issue by Deltara3** [VilariStorms/Cumsay#5]
# JOIN WEDDIT
[https://discord.gg/ukBPpCt54b](https://discord.gg/ukBPpCt54b)
<img src="https://cdn.discordapp.com/attachments/843861984441270286/843864032065880074/Screenshot_20210517-155324.png">

@Lotus-xml  is mean
<img src="https://cdn.discordapp.com/attachments/1124772967939842118/1134647592786079825/image.png">

**Comment by Deltara3** [comment]
<details><summary>Details</summary>
<p>

Cock here 
<img src="https://cdn.discordapp.com/attachments/1124772967939842118/1134643505466200246/image.png">

</p>
</details> 
<img src="https://cdn.discordapp.com/attachments/842501199693086750/843888208558161920/Screenshot_20210517-173004_Discord.jpg">

**Comment by VilariStorms** [comment]
### u/[deleted]

**Comment by VilariStorms** [comment]
### This user was suspended for violating Discord's terms of service

**Comment by VilariStorms** [comment]
### This user was suspended for violating Discord's terms of service

**Comment by VilariStorms** [comment]
### This user has been banned from r/reddit

**Comment by VilariStorms** [comment]
### [removed]

**Comment by S4ltster** [comment]
_This message has been removed_

**Comment by S4ltster** [comment]
![image](https://cdn.discordapp.com/attachments/1124772967939842118/1134644108883935342/image.png)

**Comment by VilariStorms** [comment]
> 

NO WAY BRO NINO WAS A NI

**Comment by S4ltster** [comment]
You suck

_This post was made from github mobilr_

**Comment by VilariStorms** [comment]
> You suck
> 
> _This post was made from github mobilr_

yeah and I also swallow

<img src="https://cdn.discordapp.com/attachments/842501199693086750/843602388190887946/Screenshot_20210516-173432.jpg">

**Comment by S4ltster** [comment]
mmmnnnfghhgf

*This post was made from github mobilr*

**Comment by VilariStorms** [comment]
don't listen to nerd who suck the reddit admins dicks. I'd never do that - or pull my cock out in vc like SOMEONE HERE

**Comment by S4ltster** [comment]
- [x] dick

**Comment by VilariStorms** [comment]
i like ccock mmmnnngfff <-- I do (vilari)

**Comment by S4ltster** [comment]
![Screenshot_20230727_154540.jpg](https://cdn.discordapp.com/attachments/842501199693086750/843645908021411870/Screenshot_20210517-012712_Discord.jpg)

**Comment by VilariStorms** [comment]
# APPROVED <- still spelt wrong lol (i fixed it)
<img src="https://cdn.discordapp.com/attachments/842501199693086750/843640568546590730/Screenshot_20210517-010608_Reddit.jpg">

![20230728_184608.jpg](https://github.com/VilariStorms/Cumsay/assets/87864112/787c5b26-6beb-491a-b840-6c80b48ac433)

**Comment by S4ltster** [comment]
### niger

https://github.com/VilariStorms/Cumsay/assets/87864112/159101d8-1b0f-4c1e-91d8-f8e0f74fa168

**Comment by VilariStorms** [comment]
nuh uh

**Comment by VilariStorms** [comment]
> ### niger
> Metal.Pipe.Falling.sound.effect.but.it.is.so.violent.and.loud.you.forget.your.ears.on.the.ground.mp4

i eat grass

**Comment by S4ltster** [comment]
### Me and the fbi at @VilariStorms door

https://github.com/VilariStorms/Cumsay/assets/87864112/78e34485-aa2a-4703-bad0-1bcabb828372

**Comment by S4ltster** [comment]
https://twitter.com/SimpleFacks/status/1684971991705559040?t=sNLCg0Bmy21bEuiYAq5dVw&s=19

**Comment by VilariStorms** [comment]
um twitter.. ackshully I use pronhub

**Comment by VilariStorms** [comment]
no

**Comment by S4ltster** [comment]
Ni

<img src="https://cdn.discordapp.com/attachments/842501199693086750/843895309964541952/Screenshot_20210517-175832_Discord.jpg">

**Comment by VilariStorms** [comment]
<img src="https://cdn.discordapp.com/attachments/842501199693086750/843900437131821066/Screenshot_20210517-181856_Chrome.jpg">

**Comment by Lotus-xml** [comment]
# My roommate keeps fucking his bed. How do I approach this?
I honestly don’t know how else to put it.
So for context, my roommate warned me that he “sometimes sleeptalked” at night, but I had gotten extremely unlucky with my first two roommates… they were absolutely terrible. Inconsiderate, spoiled, and disgusting. Therefore, a clean, tidy, hygienic roommate sounded great and I thought that a little sleeptalking wouldn’t hurt anyone.
The sleeptalking I can handle. The sleepfucking, on the other hand, I cannot handle. For clarification, the “sleeptalking” went from a few mumbles and groans (the first month) to nightly violent spring squeaking coming across the room.
This man will literally be pounding his mattress at 4 in the morning (it’s currently 4:30 and he’s just woken me up after rawdogging his mattress again). It got to the point where I had to use earplugs to sleep… but that caused me to miss my alarm and therefore, a class.
The other disturbing part is that he calls out names. He is currently single, and unfortunately, we have the same friend group. So occasionally, I’ll hear one of their names moaned out in the middle of the night. Here’s what woke me up half an hour ago.
squeak squeak squeak squeak squeak “uuuunghhhhhh Lauren” squeak squeak “oh fuck yeah” squeak
It only stops when 1: he climaxes. 2: he fucks the bed so violently that he bounces his himself up the bed and hits his head on the wall.
I have no idea how to approach this with him, since he’s very shy and tends to avoid/get quiet when there are sexual discussions (when he’s awake, at least.) I wouldn’t want to make it awkward, but I can’t deal with him waking me up all the time. How should I approach this?
